<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    public function findCartEnCourByUser($user)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->select('c')
                ->addSelect('u')
                ->addSelect('b')
                ->leftJoin('c.user', 'u')
                ->leftJoin('c.books', 'b')
                ->Where('c.status = :encour')
                ->setParameter('encour', 'En Cours de Commande')
                ->andwhere('c.user ='.$user->getId());
                
                
        
        $query = $qb->getQuery();
        
        return $query->getResult();
    }
}
