<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PickupspotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickupspotRepository extends EntityRepository
{
}
