<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelBookAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelBookAuthorRepository extends EntityRepository
{
}
